/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.*;

public class GameTest {
    @Test
    public void testGutterGame() {
        Game game = new Game();

        for (int i = 0; i < 20; i++) {

            game.roll(0);
        }

        assertEquals(0, game.score());
    }
}
